name: roll-together-backend
region: nyc
services:
  - name: backend
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: w4r6/roll_together
    source_dir: /
    build_command: npm run build:backend
    run_command: npm run start:prod -w roll_together_backend
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
